spring:
  application:
    name: tinylink-perf

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/tinylink_perf?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
