spring:
  application:
    name: tinylink-perf

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/tinylink_perf?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6380}
      timeout: 2000ms

server:
  port: 8080

tinylink:
  cache:
    url-ttl: ${CACHE_TTL:7d}
    null-cache-ttl: ${NULL_CACHE_TTL:2m}

