spring:
  application:
    name: tinylink

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tinylinkdb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

debug: false

## Custom environment
tinylink:
  cache:
    url-ttl: ${CACHE_TTL:7d}
    null-ttl: ${NULL_CACHE_TTL:2m}